version: 2.1
jobs:
  build:
    machine:
      # Ref: https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: mage: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Check current version of node
          command: node -v
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Run Tests
          command: npm run test-coverage
      - store_artifacts:
          path: coverage
      - run:
          name: install sonar scanner
          command: npm install -g sonarqube-scanner
      - run:
          name: Run SonarScan
          command: sonar-scanner
