version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run:
          name: Check current version of node
          command: node -v
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Run Tests
          command: npm run test:ci
      - store_artifacts:
          path: coverage
      - run:
          name: install sonar scanner
          command: sudo npm install -g sonarqube-scanner@2.7.0
      - run:
          name: Run SonarScan
          command: sonar-scanner
